version: '3.7'

# Settings and configurations that are common for all services
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /mnt/data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio:
    <<: *minio-common
    container_name: minio
    hostname: minio
    volumes:
      - type: bind
        source: /Users/danielmacedodeoliveira/dev/projetosEstudos/minio_data
        target: /mnt/data
      - type: bind
        source:  /Users/danielmacedodeoliveira/dev/projetosEstudos/minio_data/conf
        target: /etc/conf/minio.env