version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9090" /mnt/data
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - /Users/danielmacedodeoliveira/dev/projetosEstudos/volume_doker/minio_data:/mnt/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /Users/danielmacedodeoliveira/dev/projetosEstudos/volume_doker/postgres_data:/var/lib/postgresql/data

  app:
    image: flyway-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    depends_on:
      - postgres
 
  app-ocorrencia:
    image: api-ocorrencia:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - app