spring:
  application:
    name: ocorrencia-flyway

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8090