server:
  port: 8080
  servlet:
    context-path: /ocorrencia

jwt:
  secret: ${SECRET_KEY:MyVeryLongAndSecureSecretKeyThatIsAtLeast64CharactersMyVeryLongAndSecureSecretKeyThatIsAtLeast64Characters}
  expiration: 30  # 30 minutos 

spring:
  application:
    name: ocorrencia
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${USER_BANCO:postgres}
    password: ${SENHA_BANCO:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect